In [1]:
from lstm_model import *

In [2]:
def create_datasets(dict_size, seq_len, train_data_size, val_data_size):
    return Dataset(dict_size, seq_len, train_data_size, val_data_size).data()

In [3]:
train_X, train_y, val_X, val_y = create_datasets(15, 4, 5, 4)

In [4]:
train_X

array([[ 2,  0,  2,  7],
       [ 2, 11,  7,  5],
       [ 1,  9,  7,  8],
       [ 0, 14,  6,  2],
       [ 7,  5,  0,  9]])

In [5]:
train_y

array([[ 0,  2,  2,  7],
       [ 2,  5,  7, 11],
       [ 1,  7,  8,  9],
       [ 0,  2,  6, 14],
       [ 0,  5,  7,  9]])

In [6]:
val_X

array([[ 8,  0, 11,  0],
       [ 7,  1, 11,  5],
       [ 1,  1,  9, 13],
       [ 1, 10, 13,  1]])

In [7]:
val_y

array([[ 0,  0,  8, 11],
       [ 1,  5,  7, 11],
       [ 1,  1,  9, 13],
       [ 1,  1, 10, 13]])

In [8]:
dataset = Dataset(15, 4, 5, 4)

In [37]:
dataset = Dataset(10, 5, 10000, 4)
dataset.train_y

array([[4, 4, 4, 6, 8],
       [0, 6, 8, 8, 9],
       [0, 2, 4, 5, 7],
       ...,
       [3, 6, 7, 8, 9],
       [3, 3, 5, 6, 9],
       [2, 3, 5, 7, 9]])

In [38]:
dataset.train_X

array([[4, 8, 4, 6, 4],
       [8, 8, 0, 6, 9],
       [7, 4, 0, 5, 2],
       ...,
       [8, 7, 6, 3, 9],
       [3, 6, 9, 5, 3],
       [5, 2, 3, 9, 7]])

In [ ]:
model = Seq2SeqLSTM(128, 10, 0.001)

trainer = Trainer(model, dataset, SGD(), batch_size=100, learning_rate=5e-4, num_epochs = 5000)

loss_history, train_history, val_history = trainer.fit()

Epoch: 0, Loss: 11.512786548523659, Train accuracy: 0, Val accuracy: 0 
Epoch: 1, Loss: 11.512548682641885, Train accuracy: 0, Val accuracy: 0 
Epoch: 2, Loss: 11.512292906576153, Train accuracy: 0, Val accuracy: 0 
Epoch: 3, Loss: 11.512224819686283, Train accuracy: 0, Val accuracy: 0 
Epoch: 4, Loss: 11.512013000052498, Train accuracy: 0, Val accuracy: 0 
Epoch: 5, Loss: 11.512025185971346, Train accuracy: 0, Val accuracy: 0 
Epoch: 6, Loss: 11.51184135780119, Train accuracy: 0, Val accuracy: 0 
Epoch: 7, Loss: 11.51137354611884, Train accuracy: 0, Val accuracy: 0 
Epoch: 8, Loss: 11.510706536705536, Train accuracy: 0, Val accuracy: 0 
Epoch: 9, Loss: 11.50968416442209, Train accuracy: 0, Val accuracy: 0 
Epoch: 10, Loss: 11.50807013553469, Train accuracy: 0, Val accuracy: 0 
Epoch: 11, Loss: 11.505643755283812, Train accuracy: 0, Val accuracy: 0 
Epoch: 12, Loss: 11.502068310417211, Train accuracy: 0, Val accuracy: 0 
Epoch: 13, Loss: 11.4966446088943, Train accuracy: 0, Val accurac

In [25]:
model.predict(np.array([5, 6, 9, 4, 1]))

array([[6, 0, 0, 0, 9]])

In [26]:
model.predict(np.array([1,1]))

array([[9, 6]])